### ISSUE TITLE
ERROR: Service 'web' failed to build: 

### ISSUE THREAD

**Issue by tksbng** [koni/docker-php-nginx-mysql-memcached#1]
JPC13:docker tksbng00$ sudo docker-compose up
Password:
Building web
Step 1/4 : FROM php:5.6.29-fpm
 ---> 7206168763b2
Step 2/4 : ADD php.ini /usr/local/etc/php/conf.d/php.ini
 ---> Using cache
 ---> ba8efca9fef6
Step 3/4 : RUN apt-get update   && docker-php-ext-install pdo_mysql mysqli mbstring
 ---> Using cache
 ---> 508970feb6b8
Step 4/4 : RUN apt-get update   && apt-get install -y libmemcached-dev zlib1g-dev   && pecl install memcached-2.2.0   && docker-php-ext-enable memcached
 ---> Running in 7f1af472d0b7
Hit http://security.debian.org jessie/updates InRelease
Get:1 http://security.debian.org jessie/updates/main amd64 Packages [438 kB]
Ign http://deb.debian.org jessie InRelease
Hit http://deb.debian.org jessie-updates InRelease
Hit http://deb.debian.org jessie Release.gpg
Get:2 http://deb.debian.org jessie-updates/main amd64 Packages [17.6 kB]
Hit http://deb.debian.org jessie Release
Get:3 http://deb.debian.org jessie/main amd64 Packages [9049 kB]
Fetched 9504 kB in 5s (1675 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  libhashkit-dev libhashkit2 libmemcached11 libmemcachedutil2 libsasl2-dev
The following NEW packages will be installed:
  libhashkit-dev libhashkit2 libmemcached-dev libmemcached11 libmemcachedutil2
  libsasl2-dev zlib1g-dev
0 upgraded, 7 newly installed, 0 to remove and 2 not upgraded.
Need to get 971 kB of archives.
After this operation, 2865 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian/ jessie/main libhashkit2 amd64 1.0.18-4 [46.9 kB]
Get:2 http://deb.debian.org/debian/ jessie/main libmemcached11 amd64 1.0.18-4 [95.2 kB]
Get:3 http://deb.debian.org/debian/ jessie/main libmemcachedutil2 amd64 1.0.18-4 [22.3 kB]
Get:4 http://deb.debian.org/debian/ jessie/main libhashkit-dev amd64 1.0.18-4 [37.3 kB]
Get:5 http://deb.debian.org/debian/ jessie/main libsasl2-dev amd64 2.1.26.dfsg1-13+deb8u1 [310 kB]
Get:6 http://deb.debian.org/debian/ jessie/main libmemcached-dev amd64 1.0.18-4 [253 kB]
Get:7 http://deb.debian.org/debian/ jessie/main zlib1g-dev amd64 1:1.2.8.dfsg-2+b1 [206 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 971 kB in 1s (614 kB/s)
Selecting previously unselected package libhashkit2:amd64.
(Reading database ... 12250 files and directories currently installed.)
Preparing to unpack .../libhashkit2_1.0.18-4_amd64.deb ...
Unpacking libhashkit2:amd64 (1.0.18-4) ...
Selecting previously unselected package libmemcached11:amd64.
Preparing to unpack .../libmemcached11_1.0.18-4_amd64.deb ...
Unpacking libmemcached11:amd64 (1.0.18-4) ...
Selecting previously unselected package libmemcachedutil2:amd64.
Preparing to unpack .../libmemcachedutil2_1.0.18-4_amd64.deb ...
Unpacking libmemcachedutil2:amd64 (1.0.18-4) ...
Selecting previously unselected package libhashkit-dev.
Preparing to unpack .../libhashkit-dev_1.0.18-4_amd64.deb ...
Unpacking libhashkit-dev (1.0.18-4) ...
Selecting previously unselected package libsasl2-dev.
Preparing to unpack .../libsasl2-dev_2.1.26.dfsg1-13+deb8u1_amd64.deb ...
Unpacking libsasl2-dev (2.1.26.dfsg1-13+deb8u1) ...
Selecting previously unselected package libmemcached-dev.
Preparing to unpack .../libmemcached-dev_1.0.18-4_amd64.deb ...
Unpacking libmemcached-dev (1.0.18-4) ...
Selecting previously unselected package zlib1g-dev:amd64.
Preparing to unpack .../zlib1g-dev_1%3a1.2.8.dfsg-2+b1_amd64.deb ...
Unpacking zlib1g-dev:amd64 (1:1.2.8.dfsg-2+b1) ...
Setting up libhashkit2:amd64 (1.0.18-4) ...
Setting up libmemcached11:amd64 (1.0.18-4) ...
Setting up libmemcachedutil2:amd64 (1.0.18-4) ...
Setting up libhashkit-dev (1.0.18-4) ...
Setting up libsasl2-dev (2.1.26.dfsg1-13+deb8u1) ...
Setting up libmemcached-dev (1.0.18-4) ...
Setting up zlib1g-dev:amd64 (1:1.2.8.dfsg-2+b1) ...
Processing triggers for libc-bin (2.19-18+deb8u7) ...
No releases available for package "pecl.php.net/memcached"
install failed
ERROR: Service 'web' failed to build: The command '/bin/sh -c apt-get update   && apt-get install -y libmemcached-dev zlib1g-dev   && pecl install memcached-2.2.0   && docker-php-ext-enable memcached' returned a non-zero code: 1

**Comment by koni** [comment]
@tksbng 
Sorry for the late reply.
I think that the apt-get repository was out of service.
I think that it will work out after a while to start over.
